# Generated by Django 6.1.1 on 2026-09-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("Programming", "Programming"),
                    ("Web Development", "Web Development"),
                    ("AI / Machine Learning", "AI / Machine Learning"),
                    ("Database", "Database"),
                    ("Tools & Technologies", "Tools & Technologies"),
                ],
                default="Programming",
                max_length=100,
            ),
        ),
    ]
